### ISSUE TITLE
Weld SE and Weld Servlet can cooperate

### ISSUE THREAD

**Issue by mkouba** [johnament/hammock#3]
This is not an issue but more like a hint. Weld Servlet might reuse an existing BeanManager. See also https://github.com/weld/core/blob/master/environments/servlet/tests/jetty/src/test/weld-se-coop/org/jboss/weld/environment/servlet/test/se/coop/BootstrapNotNeededTest.java. So that  it's not necessary to implement custom listerners like `ws.ament.hammock.web.spi.CDIListener` but reuse the existing servlet container support.

**Comment by johnament** [comment]
Ok, thanks for the heads up.

What looks like is missing in this example is how you're overriding jetty's instance factory.

I'm closing this, as a  non-issue.

**Comment by mkouba** [comment]
> What looks like is missing in this example is how you're overriding jetty's instance factory

Weld Servlet is using Jetty's `ServletContextHandler.Decorator`: 
https://github.com/weld/core/blob/master/environments/servlet/core/src/main/java/org/jboss/weld/environment/jetty/WeldDecorator.java#L54
